import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Icons from "@/svgs/icons";
import Logo from "@/svgs/logo";
import Glyphs from "@/svgs/glyphs";
import { loadProject } from "./projectService";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

loadProject();

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("loading project");
  await loadProject();
  console.log("project loaded");
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="mx-8">{children}</main>
        <div style={{ display: "none" }}>
          <Icons />
          <Logo />
          <Glyphs />
        </div>
      </body>
    </html>
  );
}
